---

- name: Setup Grafana container
  containers.podman.podman_container:
    name: grafana
    image: docker.io/grafana/grafana-oss:latest
    state: started
    restart_policy: always
    network: homelab-net
    network_alias:
      - grafana
    volumes:
      - "/mnt/storage/grafana:/var/lib/grafana grafana/grafana-oss:Z"
