---
- name: Install packages
  ansible.builtin.package:
    name: 
      - podman
      - xfsprogs # For formating data disk
    state: present

- name: Create persistent data directories on vdb
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /mnt/storage/gitlab/config
    - /mnt/storage/gitlab/logs
    - /mnt/storage/gitlab/data
    - /mnt/storage/seaweedfs
    - /mnt/storage/coredns

- name: Pull GitLab image
  containers.podman.podman_image:
    name: docker.io/gitlab/gitlab-ce:latest
    state: present

- name: Pull SeaweedFS image
  containers.podman.podman_image:
    name: docker.io/chrislusf/seaweedfs:latest
    state: present

- name: Pull Traefik image
  containers.podman.podman_image:
    name: docker.io/library/traefik:latest
    state: present

- name: Pull CoreDNS image
  containers.podman.podman_image:
    name: docker.io/coredns/coredns:latest
    state: present

- name: Pull Vault image
  containers.podman.podman_image:
    name: docker.io/hashicorp/vault:latest
    state: present

- name: Render CoreDNS Corefile from template
  ansible.builtin.template:
    src: Corefile.j2
    dest: /mnt/storage/coredns/Corefile
    mode: '0644'

############### CoreDNS #####################

- name: Disable stub listener (free port 53)
  ansible.builtin.ini_file:
    path: /etc/systemd/resolved.conf
    section: Resolve
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0644'
  loop:
    - { option: 'DNSStubListener', value: 'no' }
    - { option: 'DNS', value: '127.0.0.1' }
    - { option: 'Domains', value: '~homelab.local'}

- name: Ensure systemd-resolved service is running and enabled
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted 
    enabled: true

- name: Start CoreDNS container
  containers.podman.podman_container:
    name: coredns
    image: docker.io/coredns/coredns:latest
    state: started
    restart_policy: always
    command: "-conf /etc/coredns/Corefile"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - "/mnt/storage/coredns/Corefile:/etc/coredns/Corefile:Z"

############### HashiCorp Vault #######################



- name: Start GitLab container
  containers.podman.podman_container:
    name: gitlab
    image: docker.io/gitlab/gitlab-ce:latest
    state: started
    restart_policy: always
    ports:
      - "8088:80"
      - "8443:443"
      - "2222:22"
    volumes:
      - "/mnt/storage/gitlab/config:/etc/gitlab:Z"
      - "/mnt/storage/gitlab/logs:/var/log/gitlab:Z"
      - "/mnt/storage/gitlab/data:/var/opt/gitlab:Z"
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.22.1.100:8088'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['initial_root_password'] = '{{ gitlab_root_pass }}'

