[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
[services]
prod-services-01 ansible_host=10.22.1.100
[control_plane]
staging-k8s-control-plane-01 ansible_host=10.22.1.10

[workers]
staging-k8s-worker-01 ansible_host=10.22.1.11
staging-k8s-worker-02 ansible_host=10.22.1.12

[cluster:children]
control_plane
workers
