---
- name: Render Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /mnt/storage/prometheus/config/prometheus.yml
    mode: '0755'

- name: Start Prometheus container
  containers.podman.podman_container:
    name: prometheus
    image: docker.io/prom/prometheus:latest
    state: started
    restart_policy: always
    network: homelab-net
    network_alias:
      - prometheus
    volumes:
      - "/mnt/storage/prometheus/config/:/root/Prometheus/:Z"

- name: Start Prometheus Node Exporter container
  containers.podman.podman_container:
    name: node-exporter 
    image: docker.io/prom/node-exporter:latest
    state: started
    restart_policy: always
    network: homelab-net
    network_alias:
      - node-exporter

- name: Start Prometheus Podman Exporter container
  containers.podman.podman_container:
    name: podman-exporters 
    image: quay.io/navidys/prometheus-podman-exporter:latest
    state: started
    restart_policy: always
    network: homelab-net
    network_alias:
      - podman-exporter
    volumes:
      - "/run/podman/podman.sock:/run/podman/podman.sock:Z"
    command: 
      - "--collector.enable-all"
