---
- name: Start Prometheus Node Exporter container
  containers.podman.podman_container:
    name: node-exporter 
    image: docker.io/prom/node-exporter:latest
    state: started
    restart_policy: always
    network: host
    volumes:
      - "/:/host:ro"
      - "/sys:/host/sys:ro"
      - "/proc:/host/proc:ro"
    command:
      - "--path.rootfs=/host"
      - "--path.sysfs=/host/sys"
      - "--path.procfs=/host/proc"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

- name: Start Prometheus Podman Exporter container
  containers.podman.podman_container:
    name: podman-exporter 
    image: quay.io/navidys/prometheus-podman-exporter:latest
    state: started
    restart_policy: always
    network: homelab-net
    network_alias:
      - podman-exporter
    env:
      CONTAINER_HOST: "tcp://socket-proxy:2375"
    command: 
      - "--collector.enable-all"

- name: Render Alloy config
  ansible.builtin.template:
    src: config.alloy.j2
    dest: /mnt/storage/alloy/config/config.alloy
    mode: '0755'
  notify: Restart alloy container

- name: Start Alloy container
  containers.podman.podman_container:
    name: alloy
    image: docker.io/grafana/alloy:latest
    state: started
    restart_policy: always
    network: homelab-net
    network_alias:
      - alloy
    volumes:
      - "/mnt/storage/alloy/config:/etc/alloy:Z"
      - "/mnt/storage/alloy/data:/var/lib/alloy/data:Z"
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
      - "--server.http.listen-addr=0.0.0.0:12345"

